#include "myLoadingScreen.h"

#include "MAGE/Game.h"
#include "MAGE/uiPrimitives.h"
#include "MAGE/view.h"

// Here's something we can only do in C++ at the moment: write our own loading screen.
// There are plans to add onDraw hooks/make small design changes to the default loading screen object so you can write them in chai, too, but where's the fun in that?

myLoadingScreen::myLoadingScreen()
	: loadingScreen()
{
}

void myLoadingScreen::draw(sf::RenderTarget & target, sf::RenderStates states) const
{
	// draw the @ symbol in the corner
	float screenHeight = theGame()->uiCamera->getSize().y;

	pDrawInfoSimple(target, states, sf::Vector2f(48.f, screenHeight - 48.f + (sin(theGame()->getSimTime().asSeconds() * 2.f) * 2.f)), "Loading!");

	// result:
	// Our loading screen will be the current state's background color, and will show the word "Loading!" in the corner.
	// The word will bounce up and down as time advances!

	// this is of course pretty simple for a loading screen.
	// for more advanced ones, you have the following variables available:
	// - loading (string generated by thing that caused the loading screen to appear)
	// - count (thing currently being loaded, from 0)
	// - countMax (number of things to load)
}
